# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8091
  port: 8002
  servlet:
    # 应用的访问路径
    context-path: /
    tomcat:
      # tomcat的URI编码
      uri-encoding: UTF-8
      # 连接数满后的排队数，默认为100
      accept-count: 1000
      threads:
        # tomcat最大线程数，默认为200
        max: 800
        # Tomcat启动初始化的线程数，默认值10
        min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.52.6.23:1433;DatabaseName=LabSystem;trustServerCertificate=true
    # url: jdbc:sqlserver://127.0.0.1:1433;DatabaseName=Dandan_System;trustServerCertificate=true
    username: ictsfc
    password: XUh7tZN9j%yTps

  # 异步加载的线程池配置
  task:
    execution:
      pool:
        max-threads: 200
        queue-capacity: 2000

  mvc:
    # 关于 Swagger 的配置
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis配置
mybatis:
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.system.**.domain
